version: "3.0"

services:
  rest:
    image: restimage:latest
    environment:
      - "MONGO_USER=${MONGO_USER}"
      - "MONGO_URL=${MONGO_URL}"
      - "MONGO_PASS=${MONGO_PASS}"
      - "DOCKER_SERVER=${DOCKER_SERVER}"
    networks:
      test:
        aliases:
          - rest
    ports:
      - "8081:8081"

  scraper:
    image: scrimage:latest
    networks:
      - test
    depends_on:
      - rest
    deploy:
      replicas: 1

networks:
  test:
