version: "3"

services:
  scraper:
    image: scrimage:latest
    environment:
      - REST=http://192.168.0.1:8081
    networks:
      - mynet
    deploy:
      replicas: 3

networks:
  mynet:
    external: true